<!DOCTYPE html PUBLIC ""
	"">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>UPI generated by VisualSlideshow.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="UPI, Visual Slideshow, Slideshow For Website, Blog Slideshow" />
	<meta name="description" content="UPI created with Visual Slideshow, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start VisualSlideShow.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine/css/slideshow.css" media="screen" />
	<style type="text/css">.slideshow a#vlb{display:none}</style>
	<script type="text/javascript" src="engine/js/mootools.js"></script>
	<script type="text/javascript" src="engine/js/visualslideshow.js"></script>
	<!-- End VisualSlideShow.com HEAD section -->
</head>
<body style="background-color:#d7d7d7">
	<!-- Start VisualSlideShow.com BODY section -->
	<div id="show" class="slideshow">
	<div class="slideshow-images">
<a href="#"><img id="slide-0" src="data/images/E1.jpg" alt="SMK N 2 PARIAMAN" title="SMK N 2 PARIAMAN /></a>
<a href="#"><img id="slide-1" src="data/images/IMG_8869.jpg" alt="SMK N 2 PARIAMAN" title="SMK N 2 PARIAMAN" /></a>
<a href="#"><img id="slide-2" src="data/images/IMG_0667.jpg" alt="labteknik" title="labteknik" /></a>
<a href="#"><img id="slide-3" src="data/images/IMG_8873.jpg" alt="SMK N 2 PARIAMAN" title="SMK N 2 PARIAMAN " /></a>

</div>
<div class="slideshow-thumbnails">
<ul>
<li><a href="#slide-0"><img src="data/thumbnails/E1.jpg" alt="SMK N 2 PARIAMAN" /></a></li>
<li><a href="#slide-1"><img src="data/thumbnails/IMG_8869.jpg" alt="SMK N 2 PARIAMAN" /></a></li>
<li><a href="#slide-2"><img src="data/thumbnails/IMG_0667.jpg" alt="labteknik" /></a></li>
<li><a href="#slide-3"><img src="data/thumbnails/IMG_8873.jpg" alt="SMK N 2 PARIAMAN" /></a></li>

</ul>
</div>
<a id="vlb" href="http://visualslideshow.com">Slide Show Creator by VisualSlideshow.com v1.7</a>
	<div class="slideshow-frame"></div>
	</div>
	<!-- End VisualSlideShow.com BODY section -->
</body>
</html>